export const localImages = {
  logo: require("app/assets/images/logo.png"),
  logo2: require("app/assets/images/logo_alt.png"),
  bg: require("app/assets/images/bg.png"),
  avatarPlaceholder: require("app/assets/images/avatar_placeholder.png"),
  driverPlaceHoder: require("app/assets/images/user_placeholder/driver.png"),
  parentPlaceHoder: require("app/assets/images/user_placeholder/parent.png"),
  teacherPlaceHoder: require("app/assets/images/user_placeholder/teacher.png"),
  functionIconHeading1: require("app/assets/images/function/function-ico-heading-1.png"),
  functionIconHeading2: require("app/assets/images/function/function-ico-heading-2.png"),
  functionIconHeading3: require("app/assets/images/function/function-ico-heading-3.png"),
  functionIcon1: require("app/assets/images/function/function-ico-1.png"),
  functionIcon2: require("app/assets/images/function/function-ico-2.png"),
  functionIcon3: require("app/assets/images/function/function-ico-3.png"),
  functionIcon4: require("app/assets/images/function/function-ico-4.png"),
  functionIcon5: require("app/assets/images/function/function-ico-5.png"),
  functionIcon6: require("app/assets/images/function/function-ico-6.png"),
  functionIcon7: require("app/assets/images/function/function-ico-7.png"),
  functionIcon8: require("app/assets/images/function/function-ico-8.png"),
  functionIcon9: require("app/assets/images/function/function-ico-9.png"),
  functionIcon10: require("app/assets/images/function/function-ico-10.png"),
  functionImgCardPlaceholder1: require("app/assets/images/function/function-img-placeholder-1.png"),
  functionImgCardPlaceholder2: require("app/assets/images/function/function-img-placeholder-2.png"),
  functionImgCardPlaceholder3: require("app/assets/images/function/function-img-placeholder-3.png"),
  functionImgCardPlaceholder4: require("app/assets/images/function/function-img-placeholder-4.png"),
  MenuIconClock: require("app/assets/images/menu/menu-img-clock.png"),
};
